version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: base
    depends_on:
      - database
    volumes:
      - ./src:/home/node/app/src
    container_name: ecommerce-service
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm run migration:run && npm run start:dev"]
    networks:
      - commerce

  database:
    image: postgres:13
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - commerce

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_METAL=1
    networks:
      - commerce
    command: "serve"

volumes:
  postgres-data:
    driver: local
  ollama-data:
    driver: local

networks:
  commerce: